name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Debug - Show env.js before replacement
        run: |
          echo "=== env.js ANTES da substituição ==="
          cat env.js
          echo "================================="

      - name: Replace environment variables
        run: |
          sed -i "s/{{FIREBASE_API_KEY}}/${{ secrets.FIREBASE_API_KEY }}/g" env.js
          sed -i "s/{{FIREBASE_AUTH_DOMAIN}}/${{ secrets.FIREBASE_AUTH_DOMAIN }}/g" env.js
          sed -i "s/{{FIREBASE_PROJECT_ID}}/${{ secrets.FIREBASE_PROJECT_ID }}/g" env.js
          sed -i "s/{{FIREBASE_STORAGE_BUCKET}}/${{ secrets.FIREBASE_STORAGE_BUCKET }}/g" env.js
          sed -i "s/{{FIREBASE_MESSAGING_SENDER_ID}}/${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}/g" env.js
          sed -i "s/{{FIREBASE_APP_ID}}/${{ secrets.FIREBASE_APP_ID }}/g" env.js

      - name: Debug - Show env.js after replacement
        run: |
          echo "=== env.js DEPOIS da substituição ==="
          cat env.js
          echo "===================================="

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "."

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
